version: '{build}-{branch}'
image: Visual Studio 2017

skip_commits:
  files:
    - '**/*.md'

build_script:
- ps: .\build.ps1

after_build:
- ps: .\pack.ps1

artifacts:
- path: '**\artifacts\nuget\*.nupkg'
  name: NuGet
  