version: '{build}-{branch}'
image: Visual Studio 2017

skip_commits:
  files:
    - '**/*.md'

build_script:
- ps: .\build.ps1

after_build:
- ps: .\pack.ps1
  
artifacts:
- path: '**\artifacts\nuget\*.nupkg'
  name: Nuget
- path: '**\artifacts\myget\*.nupkg'
  name: Myget
  
deploy:

- provider: NuGet
  api_key:
    secure: daQCsScgPEP6DIMLmaEdEf7W4UrrFO8h2IVZjlEkAKzYvTMaBc1l+hVkjmc8RkDx
  artifact: NuGet
  on:
    appveyor_repo_tag: true   
    
- provider: NuGet
  server: https://www.myget.org/F/phnx47-beta/api/v2/package
  api_key:
    secure: Smuwoi47XyX6b6x66VpPnnL96F3cl1nukALrFnZo1Oony38dzouByG7pnt6DX4HT
  symbol_server: https://www.myget.org/F/phnx47-beta/symbols/api/v2/package
  artifact: MyGet
  on:
    branch: master
    appveyor_repo_tag: false